### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by davixcky** [FONQRI/MaterialUiSamplesQtQml#1]
Hola, te sugiero que agregues imágenes en el README para ver cómo sería la ui

Gracias

_Enviado desde mi Moto E (4) usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by FONQRI** [comment]
hello 
Thanks for letting me know .
because most of this ui was animations i decided to add a video instead of screenshots . you can download it from github now i put it in project and also i added its link to README.md .
thanks again .

**Comment by davixcky** [comment]
Thanks for answering

**Comment by FONQRI** [comment]
you're welcome.
